const STANCES={X55:'3',X58:'4',X56:'5',X61:'5',X59:'6',X59A:'6'};
let data=[],filter='all',query='';
const $=s=>document.querySelector(s);
const datePicker=$('#datePicker');
const augustStart='2026-08-01',augustEnd='2026-08-31';
function defaultDate(){const n=new Date(),iso=n.toISOString().slice(0,10);return iso>=augustStart&&iso<=augustEnd?iso:augustStart}
datePicker.value=defaultDate();
function key(j){return `${datePicker.value}|${j.id||[j.time,j.route,j.destination,j.stance].join('|')}`}
function seenSet(){return new Set(JSON.parse(localStorage.getItem('edinburgh-seen')||'[]'))}
function saveSeen(set){localStorage.setItem('edinburgh-seen',JSON.stringify([...set]))}
function runsForDate(){const d=datePicker.value;return data.filter(j=>!j.date||j.date===d).sort((a,b)=>(a.time||'').localeCompare(b.time||''))}
function halbeath(j){const names=(j.stops||[]).map(s=>(s.name||s.stop||'').toLowerCase());const dest=(j.destination||'').toLowerCase();if(dest.includes('halbeath'))return 'Terminates at Halbeath';if(names.some(n=>n.includes('halbeath')))return 'Via Halbeath';return 'Does not serve Halbeath'}
function render(){const seen=seenSet();const all=runsForDate();const matches=all.filter(j=>{const isSeen=seen.has(key(j));const f=filter==='all'||(filter==='seen'&&isSeen)||(filter==='unseen'&&!isSeen);const text=`${j.route} ${j.destination} ${j.via||''}`.toLowerCase();return f&&text.includes(query.toLowerCase())});
$('#seenCount').textContent=all.filter(j=>seen.has(key(j))).length;$('#totalCount').textContent=all.length;$('#remainingCount').textContent=all.filter(j=>!seen.has(key(j))).length;
const list=$('#departureList');list.innerHTML='';
if(!matches.length){list.innerHTML=`<div class="empty">${all.length?'No departures match this filter.':'No published Stagecoach departures are loaded for this date yet.'}</div>`;return}
for(const j of matches){const isSeen=seen.has(key(j));const card=document.createElement('article');card.className=`departure${isSeen?' seen':''}`;const h=halbeath(j);card.innerHTML=`<div class="time">${j.time||'--:--'}</div><div class="route">${j.route||'?'}</div><div class="details"><button type="button"><strong>${j.destination||'Destination not published'}</strong><small>${j.via?`via ${j.via} · `:''}Tap for all stops</small><div class="badges"><span class="badge">Scheduled</span><span class="badge halbeath">${h}</span></div></button></div><div class="stance" title="Stance">${j.stance||STANCES[j.route]||'?'}</div><div class="seen-control"><label><input type="checkbox" ${isSeen?'checked':''}> Seen</label></div>`;
card.querySelector('.details button').onclick=()=>openJourney(j,h);card.querySelector('input').onchange=e=>{const s=seenSet();e.target.checked?s.add(key(j)):s.delete(key(j));saveSeen(s);render()};list.append(card)} }
function openJourney(j,h){$('#dialogMeta').textContent=`${j.time||''} · Service ${j.route||''} · Stance ${j.stance||STANCES[j.route]||'not published'}`;$('#dialogTitle').textContent=j.destination||'Journey';$('#halbeathDetail').textContent=h;const ol=$('#stopList');ol.innerHTML='';(j.stops||[]).forEach(s=>{const li=document.createElement('li');li.innerHTML=`${s.name||s.stop||''}${s.time?`<time>${s.time}</time>`:''}`;ol.append(li)});if(!(j.stops||[]).length)ol.innerHTML='<li>Stop-by-stop pattern has not yet been imported for this journey.</li>';$('#liveLink').href=j.liveUrl||`https://bustimes.org/search?q=${encodeURIComponent(`${j.route||''} Edinburgh Bus Station`)}`;$('#journeyDialog').showModal()}
async function load(){try{const r=await fetch(`data/edinburgh-stagecoach.json?v=${Date.now()}`);if(!r.ok)throw new Error();const json=await r.json();data=Array.isArray(json)?json:(json.departures||[]);$('#dataNotice').textContent=data.length?`Published scheduled timetable loaded. ${data.length} journey records available. Times are not live predictions.`:'The timetable file is present but contains no August journeys.'}catch{$('#dataNotice').textContent='The official August timetable has not been imported yet. No sample or invented times are being shown.'}render()}
function clock(){const n=new Date();$('#clock').textContent=n.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});$('#todayLabel').textContent=n.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
$('#search').oninput=e=>{query=e.target.value.trim();render()};datePicker.onchange=render;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#clearChecks').onclick=()=>{if(confirm(`Clear all Seen checks for ${datePicker.value}?`)){const s=seenSet();[...s].filter(k=>k.startsWith(datePicker.value+'|')).forEach(k=>s.delete(k));saveSeen(s);render()}};$('#closeDialog').onclick=()=>$('#journeyDialog').close();clock();setInterval(clock,30000);load();